[package]
name = "clause-ai"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenv = "0.15.0"
#This is dont env this will load Envirment variable , specifically ".env" file it has api key.
rocket = "0.5.1"
#This will be our server for rust crate.